* Emacs Configuration

This is file config.org: Main emacs configuration.

** File Setup

*Must* be first line of the file.

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

** Load Path

In my local /lisp subdirectory, I've got some third-party projects
which should be loaded from local files.

#+begin_src emacs-lisp
(defun add-subdirs-to-load-path (parent-directory)
  "Add PARENT-DIRECTORY and its immediate child directories to `load-path'."
  (let ((default-directory parent-directory))
    (add-to-list 'load-path default-directory)
    (normal-top-level-add-subdirs-to-load-path)))

;; (add-subdirs-to-load-path "/opt/homebrew/share/emacs/site-lisp")
(add-subdirs-to-load-path
 (directory-file-name
  (concat (expand-file-name user-emacs-directory) "my_emacs/lisp")))
#+end_src

** Customization
Set up seperate file for use by emacs customzation.

I prefer to set customization options in the ~use-package~ declaration
for each package, but on-the-fly or local-only customizations will go
to this file.

#+begin_src emacs-lisp
 (setq custom-file "~/.config/emacs/my_emacs/custom.el")
 (load custom-file)
#+end_src

** Customizing Emacs Itself
We can use ~use-package~ to configure emacs itself as a 'pseudo-package'.

#+begin_src emacs-lisp
  (use-package
    emacs

    :config
    (setq frame-title-format "%b")
    (setq-default indent-tabs-mode nil)
    ;; enable built-in completion package
    (ido-mode t)

    :bind
    (("M-/" . 'hippie-expand)
     ("C-x C-b" . 'ibuffer)
     ("C-s" . 'isearch-forward-regexp)
     ("C-r" . 'isearch-backward-regexp)
     ("C-M-s" . 'isearch-forward)
     ("C-M-r" . 'isearch-backward))

    :custom
    (ido-enable-flex-matching t)
    (ido-big-directories '("node_modules" "\\.?venv"))
    (ido-cannot-complete-command 'ido-completion-help)
    (ido-ignore-directories '("\\`CVS/" "\\`\\.\\./" "\\`\\./" "\\`__pycache__/"))
    (ido-use-filename-at-point nil)
    (ido-use-url-at-point t)
    (ido-use-virtual-buffers 'auto)

    (save-place-mode t)
    (show-paren-mode 1)
    (global-auto-revert-mode 1)
    (apropos-do-all t)
    ;; put file backups in single directory, not in same directory with '~' appended.
    (backup-directory-alist
     `(("." . ,(concat user-emacs-directory "backups"))))
    (column-number-mode t nil nil "displays current column in mode line")
    (default-frame-alist
     '((horizontal-scroll-bars)
       (vertical-scroll-bars)
       (width . 180)
       (height . 70))
     nil
     nil
     "set initial window size, and enable scroll bars") ;; see also early-init.el
    (mouse-yank-at-point t)
    (save-interprogram-paste-before-kill t)
    (save-place-file (concat user-emacs-directory "places"))
    (select-enable-clipboard t nil nil "integrate emacs with system clipboard")
    (select-enable-primary t)
    (sentence-end-double-space nil)
    (uniquify-buffer-name-style 'post-forward-angle-brackets)
    (user-email-address "lloyd.flanagan@proton.me")
    (selection-coding-system 'utf-8))
#+end_src

** Packages
Eventual goal is to remove these from customization entirely, and use
~use-package~ for all.

*** Ido and amx
There are (at least) two major emacs packages to enable
auto-completion: "ivy" and "ido". Ivy is full-featured and includes
"counsel", which modifies emacs commands to use ivy. However, it looks
not to be actively maintained, and I've come to prefer "ido". It's
builtin to Emacs, which is convenient.

The [[https://github.com/DarwinAwardWinner/amx]["amx" package]] leverages "ido" to add features to the Emacs
~execute-extended-command~ function (M-x).

#+begin_src emacs-lisp
(use-package amx)
#+end_src

*** Treemacs

Set up treemacs, the directory tree sidebar.

#+begin_src emacs-lisp
(use-package
 treemacs
 :ensure t
 :defer t
 :init
 (with-eval-after-load 'winum
   (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
 :config
 (progn
   (setopt
    treemacs-collapse-dirs
    (if treemacs-python-executable
        3
      0)
    treemacs-display-in-side-window t)
   (treemacs-follow-mode t)
   (treemacs-filewatch-mode t)
   (treemacs-fringe-indicator-mode 'always)
   (when treemacs-python-executable
     (treemacs-git-commit-diff-mode t))

   (pcase (cons
           (not (null (executable-find "git")))
           (not (null treemacs-python-executable)))
     (`(t . t) (treemacs-git-mode 'deferred))
     (`(t . _) (treemacs-git-mode 'simple)))

   (treemacs-hide-gitignored-files-mode nil))
 :bind
 (:map
  global-map
  ("M-0" . treemacs-select-window)
  ("C-x t 1" . treemacs-delete-other-windows)
  ("C-x t t" . treemacs)
  ("C-x t d" . treemacs-select-directory)
  ("C-x t B" . treemacs-bookmark)
  ("C-x t C-t" . treemacs-find-file)
  ("C-x t M-t" . treemacs-find-tag)))
#+end_src

**** Treemacs-icons-dired

Treemacs icons for Dired.  Code is based on all-the-icons-dired.el

#+begin_src emacs-lisp
(use-package treemacs-icons-dired
  :after (treemacs)
  :hook (dired-mode . treemacs-icons-dired-enable-once)
  :ensure t)
#+end_src

**** Treemacs-magit -- integrate git with treemacs.

#+begin_src emacs-lisp
(use-package treemacs-magit
  :after (treemacs magit)
  :ensure t)
#+end_src

**** Treemacs start on boot.

Initialiser specifically to start treemacs as part of your init
file. Ensures that all visual elements are present which might
otherwise be missing because their setup requires an interactive
command or a post-command hook.

#+begin_src emacs-lisp
(treemacs-start-on-boot)
#+end_src

** End of File

#+begin_src emacs-lisp
;;; init.el ends here
#+end_src

