# -*- fill-column: 80; -*-
* Emacs Configuration

This is file config.org: Main emacs configuration.

** File Setup

*Must* be first line of the file.

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
#+end_src

** Legal Stuff

Legal/copyright notice for the generated file. All terms are asserted to apply to
this file also.

#+begin_src emacs-lisp
;;; config.el -- Non-site-specific initialization -*- lexical-binding: t; -*-

;; Copyright © 2025 A. Lloyd Flanagan
;;
;; Author: A. Lloyd Flanagan <lloyd.flanagan@proton.me>
;; Maintainer: A. Lloyd Flanagan <lloyd.flanagan@proton.me>
;; Created: 2014
;; Version: ??

;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.
;;
;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to
;; the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
;; Boston, MA 02111-1307, USA.
;;
;; This file is not part of GNU Emacs.

#+end_src

** Helper Function

Quick function to make refering to other config files easier.

#+begin_src emacs-lisp
(defun get-config-file (filename)
  (expand-file-name filename (expand-file-name user-emacs-directory "my_emacs/")))
#+end_src

** Load Path

In my local ~/lisp~ subdirectory, I've got some third-party projects
which should be loaded from local files.

#+begin_src emacs-lisp
(add-to-list 'load-path (expand-file-name "my_emacs" user-emacs-directory))

;; user-lisp-directory is a new feature, fallback when it's not present
(unless (boundp 'user-lisp-directory)
  (add-to-list
   'load-path
   (directory-file-name
    (expand-file-name "my_emacs/lisp/org-contrib/lisp" user-emacs-directory))))
#+end_src

** Miscellaneous Optimizations

A grab-bag of configuration options from various startup frameworks, collected
together by [[https://emacsredux.com/blog/2026/04/07/stealing-from-the-best-emacs-configs/][Bozhidar Batsov]].

*** Drop Left-to-Right Text

Turn off the bidirectional algorithm. This optimizes text display and editing by
telling emacs to assume text is left-to-right. Obviously, if you frequently work
with right-to-left text, don't do this.

#+begin_src emacs-lisp
(setq-default
 bidi-display-reordering 'left-to-right
 bidi-paragraph-direction 'left-to-right)
(setq bidi-inhibit-bpa t)
#+end_src

*** Smooth Input Experience

Tell emacs not to do fontification (syntax highlighting) during input, which can
make input slower. Emacs will wait for idle time to do fontification.

#+begin_src emacs-lisp
(setq redisplay-skip-fontification-on-input t)
#+end_src

*** Better Communicate With External Processes

From the blog entry:

#+BEGIN_QUOTE
The default *~read-process-output-max~* is 64KB, which is still quite
conservative. Modern LSP servers like rust-analyzer or clangd routinely send
multi-megabyte responses. Bumping this reduces the number of read calls Emacs
has to make:
#+END_QUOTE

#+begin_src emacs-lisp
(setq read-process-output-max (* 4 1024 1024)) ; 4MB
#+end_src

#+BEGIN_QUOTE
If you have several windows visible, Emacs draws a cursor in each of them – even
the ones you’re not working in. It also highlights selections in non-focused
windows.
#+END_QUOTE

This behavior has miniscule performance impact, but some people find the phantom
cursors annoying. I'm one of them.

#+begin_src emacs-lisp
(setq-default cursor-in-non-selected-windows nil)
(setopt highlight-nonselected-windows nil)
#+end_src

*** Make Shell Scripts Executable

Save a file with a shebang (*~#!~*), and Emacs *~chmod +x~*​es it for you. One of
those things that should arguably be a default.

**** TODO: for python mode, set exec if 'if __name__ === "main"' is present.

#+begin_src emacs-lisp
(add-hook 'after-save-hook #'executable-make-buffer-file-executable-if-script-p)
#+end_src

** Clipboard Tweaks

More optimizations from the blog post by [[https://emacsredux.com/blog/2026/04/07/stealing-from-the-best-emacs-configs/][Bozhidar Batsov]].

*** Keep Clipbard Contents

#+BEGIN_QUOTE
Here’s a scenario: you copy a URL from your browser, switch to Emacs, kill a
line with C-k, and then try to yank the URL you copied earlier with C-y. Gone.
The kill replaced it on the clipboard.

This setting makes Emacs save the existing clipboard content into the kill ring
before overwriting it:
#+END_QUOTE

#+begin_src emacs-lisp
(setopt save-interprogram-paste-before-kill t)
#+end_src

*** De-Duplicate Kill Ring

#+begin_src emacs-lisp
(setopt kill-do-not-save-duplicates t)
#+end_src

*** Save Kill Ring

#+begin_src emacs-lisp
(setopt savehist-additional-variables '(search-ring regexp-search-rhig kill-ring))
#+end_src

*** Sane Syntax in re-builder (Multiple Configs)

Use reasonable syntax (instead of having to escape everything) for re-builder
(M-x re-builder), an interactive tool for developing regular expressions.

#+begin_src emacs-lisp
(setopt reb-re-syntax 'string)
#+end_src

*** Fix find-file-at-point

The *~ffap~* function is a.k.a. *~find-file-at-point~*, and I only use it for
files. So it's a real problem when it tries to interpret the filenama as a URL,
so I turn it off.

#+begin_src emacs-lisp
(setq ffap-machine-p-known 'reject)
#+end_src

*** Filter Completion Suggestions

The default filter for M-x completion shows all commands, whether they apply to
the current buffer or not. This setting tells it to filter out commands that
have been delared to not apply to this buffer.

- command-completion-default-include-p: filters commands declared to only apply
  to modes that aren't enabled in the current buffer.

- transient-command-completion-not-suffix-only-p: filters commands that have
  been declared to only act as [[info:Transient][transient]] suffixes.

#+begin_src emacs-lisp
  (defun my-completion-predicate (symbol buffer)
    "Combines command completion predicates to make completion list shorter."
    (and (command-completion-default-include-p symbol buffer)
         (transient-command-completion-not-suffix-only-p symbol buffer)))

  (setopt read-extended-command-predicate #'my-completion-predicate)
#+end_src

** Easy Customization

Set up separate file for use by emacs customization.

I prefer to set customization options in the ~use-package~ declaration for each
package, but on-the-fly or local-only customizations will go to this file.

#+begin_src emacs-lisp
;; custom-file is built-in global variable.
(setq custom-file (get-config-file "custom.el"))
(load custom-file 'no-error 'no-message)
#+end_src

We need to add the *melpa* package source to ~package-archives~.

#+begin_src emacs-lisp
(setopt
 package-archives
 '(("gnu" . "https://elpa.gnu.org/packages/") ("nongnu" . "https://elpa.nongnu.org/nongnu/")
   ("melpa" . "https://melpa.org/packages/")))
#+end_src

** Secrets File

This local file is for global variables with values which should not
be checked in with source control, such as passwords and API keys.

#+begin_src emacs-lisp
(require 'my-secrets)
#+end_src

** Uniquify

Uniquify is a part of emacs which is not loaded by default, but it can
be ~require~d to change the way buffers are named when editing
different files with the same name. From the source file:

#+BEGIN_QUOTE
Emacs's traditional method for making buffer names unique adds <2>, <3>, etc. to
the end of (all but one of) the buffers. This file replaces that behavior, for
buffers visiting files and Dired buffers, with a uniquification that adds parts
of the file name until the buffer names are unique.
#+END_QUOTE

#+begin_src emacs-lisp
(require 'uniquify)
(setopt uniquify-buffer-name-style 'post-forward-angle-brackets)
#+end_src

** Server

(server-start)

** Customizing Emacs Itself

We can use ~use-package~ to configure emacs itself as a 'pseudo-package'.

#+begin_src emacs-lisp
(use-package
 emacs

 :bind
 (("M-/" . #'hippie-expand)
  ("C-x C-b" . #'ibuffer)
  ("C-s" . #'isearch-forward-regexp)
  ("C-r" . #'isearch-backward-regexp)
  ("C-M-s" . #'isearch-forward)
  ("C-M-r" . #'isearch-backward)
  ("C-x M-r" . #'remember)

  ("C-x M-R" .
   (lambda ()
     (interactive)
     (let ((current-prefix-arg '(4)))
       (call-interactively #'remember))))
  ("s-q" . nil)
  ;; runs save-buffers-kill-emacs by default, but too easy to hit by accident
  )

 :config
 (global-auto-revert-mode)
 (when window-system
   (tool-bar-mode -1))
 (blink-cursor-mode -1)
 (when (equal system-type 'darwin)
   (setopt trash-directory "~/.Trash"))

 ;; set coding systems used to Unicode standard
 (set-terminal-coding-system 'utf-8)
 (set-keyboard-coding-system 'utf-8)
 (prefer-coding-system 'utf-8)

 (ido-mode t)
 (ido-everywhere t)

 ;; be careful with this: it can conflict with version control hooks such as
 ;; precommit (see alse ~kill-buffer-delete-auto-save-files~
 (auto-save-visited-mode t)

 (column-number-mode t) ;; displays current column in mode line
 (setq-default indent-tabs-mode nil)

 (save-place-mode t)
 (show-paren-mode t)
 (transient-mark-mode t) ;; visually highlight selected region

 (minibuffer-regexp-mode 1) ;; syntax highlighting for writing regexps

 :custom
 (ido-big-directories '("node_modules" "\\.?venv"))
 (ido-cannot-complete-command #'ido-completion-help)
 (ido-ignore-directories '("\\`CVS/" "\\`\\.\\./" "\\`\\./" "\\`__pycache__/"))
 (ido-use-filename-at-point nil)
 (ido-use-url-at-point t)
 (ido-use-virtual-buffers 'auto)
 ;; auto-save options
 (kill-buffer-delete-auto-save-files t)
 (delete-by-moving-to-trash t) ;; use system trash can for deleted files
 (apropos-do-all t)
 ;; put file backups in single directory, not in same directory with '~'
 ;; appended.
 (backup-directory-alist `(("." . ,(concat user-emacs-directory "backups"))))

 ;; old libraries are creating temporary buffers without the lexical-binding
 ;; tag. Since I don't need that warning, clean up *Warnings* a bit by silencing
 ;; it

 (warning-suppress-types '((files missing-lexbind-cookie)))

 (server-log t)
 ;; use value of `truncate_lines' even in windows narrower than frame
 (truncate-partial-width-windows nil)
 (use-file-dialog nil)
 (visible-bell (not (equal system-type 'darwin))) ;;bad on mac
 ;; don't show package in menu if higher-priority package is found
 (package-menu-hide-low-priority t)

 ;; Python setup: assume mise manages uv, and uv creates .venv in each project.
 ;; Prepend .venv/bin to exec-path so python3 resolves to the project venv.
 (python-shell-exec-path '("./.venv/bin"))
 (python-interpreter "python3")
 (python-shell-interpreter "python3")
 (echo-keystrokes 0.1) ;; reduce lag in echo keystroke to screen
 (fill-column 80)
 ;; use as much syntax highlighting as possible, by default
 (font-lock-maximum-decoration t)
 (inhibit-startup-message t) ;; turn off Emacs splash screen
 (initial-scratch-message nil)
 (mouse-yank-at-point t)
 (save-interprogram-paste-before-kill t)
 (save-place-file (expand-file-name "places" user-emacs-directory))
 (select-enable-clipboard t) ;; integrate emacs with system clipboard
 (select-enable-primary t)
 (selection-coding-system 'utf-8)

 ;; don't automatically double space after sentence end -- obsolete style
 (sentence-end-double-space nil)

 :hook (prog-mode . display-line-numbers-mode)
 ;; Treat CamelCaseSubWords as separate words in every programming mode.
 (prog-mode . subword-mode))
#+end_src

** Default Font

Set up with my current programming font, Fira Code. You must have Fira
Code installed on your system for this to work.

#+begin_src emacs-lisp
(set-face-attribute 'default nil
                    :family "Fira Code"
                    :height 160
                    :weight 'normal
                    :slant 'normal
                    :width 'normal)
#+end_src

** Packages

Eventual goal is to remove these from customization entirely, and use
~use-package~ for all.

NOTE: ~use-package~ is installed by ~init.el~.

*** EditorConfig

There is a standard file named .editorconfig that sets a few options for an
editor, helping ensure everyone working on a project uses the same settings.
This sets up Emacs to get config settings from that file.

#+begin_src emacs-lisp
(use-package editorconfig :ensure t :config (editorconfig-mode 1))
#+end_src

*** Themes

#+begin_src emacs-lisp
(use-package batppuccin
  :vc (:url "https://github.com/bbatsov/batppuccin-emacs" :rev :newest)
  :config
  (load-theme 'batppuccin-latte t))
#+end_src

*** Better Mode Line

[[https://github.com/Malabarba/smart-mode-line][Smart-mode-line]] is a sexy mode-line for Emacs. It aims to be easy to
read from small to large monitors by using colors, a prefix feature,
and smart truncation.

#+begin_src emacs-lisp
(use-package smart-mode-line :config (sml/setup))
(use-package
 smart-mode-line-powerline-theme
 :config (sml/apply-theme 'powerline))
#+end_src

*** Ido and amx

There are (at least) three major emacs packages to enable
auto-completion: "ivy", "company", and "ido". Ivy is full-featured and
includes "counsel", which modifies emacs commands to use ivy. However,
it looks not to be actively maintained, and I've come to prefer "ido".
It's builtin to Emacs, which is convenient.

The [[https://github.com/DarwinAwardWinner/amx]["amx" package]] leverages "ido" to add features to the Emacs
~execute-extended-command~ function (M-x).

#+begin_src emacs-lisp
(use-package amx
    :ensure t
    :config (amx-mode 1))
#+end_src

#+BEGIN_QUOTE
This package replaces stock emacs completion with ido completion wherever it is
possible to do so without breaking things (i.e. what you were probably hoping
for when you set ido-everywhere to t).
#+END_QUOTE

#+begin_src emacs-lisp
(use-package ido-completing-read+
  :config
    (ido-ubiquitous-mode 1))
#+end_src

*** Page-break Lines

This is a neat little package that displays embedded ctrl-L characters
as horizontal lines. This helps break up the file on the screen, not
just when printed.

#+begin_src emacs-lisp
(use-package page-break-lines :config (global-page-break-lines-mode))
#+end_src

*** Better folding: Kirigami

Kirigami provides code folding for buffers that don't use tree-sitter
(where ~treesit-fold~ already handles folding).

#+begin_src emacs-lisp
(use-package
 kirigami
 :commands kirigami-mode
 :config
 (defun my/kirigami-enable-if-no-treesit ()
   "Enable `kirigami-mode' in buffers without active tree-sitter parsers."
   (unless (treesit-parser-list)
     (kirigami-mode 1)))
 (add-hook 'prog-mode-hook #'my/kirigami-enable-if-no-treesit))
#+end_src

*** Clean up Whitespace

This package automatically strips extra whitespace from the end of
lines.

#+begin_src emacs-lisp
(use-package whitespace-cleanup-mode :config (global-whitespace-cleanup-mode 1))
#+end_src

*** Which-key

Displays available key bindings in a popup after pressing a prefix key. Built-in
as of Emacs 30.

#+begin_src emacs-lisp
(if (< emacs-major-version 30)
    (use-package
     which-key
     :ensure nil ;; defer to built-in
     :config (which-key-mode))
  (use-package which-key :ensure t :config (which-key-mode)))
#+end_src

*** Magit

Magit is a package to provide a git interface inside of Emacs. It relies on
a version of ~transient~ more recent than the built-in one, so we add an explicit
~use-package~ call for it.

#+begin_src emacs-lisp
(use-package transient :pin "melpa" :ensure t)

(use-package magit :defer t)
#+end_src

*** Treemacs

Set up treemacs, the directory tree sidebar. See [[https://github.com/Alexander-Miller/treemacs][treemacs repo]] for all
the gory details.

#+begin_src emacs-lisp
(use-package
 treemacs
 :ensure t
 :defer nil
 :init
 (require 'cua-base)
 (with-eval-after-load 'winum
   (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
 :config
 (when treemacs-python-executable
   (treemacs-git-mode 'extended)
   (treemacs-git-commit-diff-mode t)
   (treemacs-hide-gitignored-files-mode t))
 ;; treemacs-git-commit-diff fires async callbacks for all workspace projects,
 ;; including ones not currently visible in the buffer.  When the callback
 ;; tries to annotate a path whose project node doesn't exist in the buffer,
 ;; treemacs-project->position receives nil and crashes.  Guard against that.
 (with-eval-after-load 'treemacs-git-commit-diff
   (advice-add
    'treemacs-apply-single-annotation
    :before-while (lambda (path) (treemacs-is-path path :in-workspace))))
 (treemacs-start-on-boot)
 :custom
 (treemacs-project-follow-mode t)
 (treemacs-filewatch-mode t)
 (treemacs-is-never-other-window t)
 ;; follow mode makes it difficult to find file that are not on-screen
 (treemacs-follow-mode nil)
 (treemacs-follow-after-init nil)

 :bind
 ;; M-0 intentionally omitted here; scoped to winum-keymap in :init above
 ;; to avoid shadowing digit-argument globally.
 ;; C-x t 1 → tab-close-other (Emacs 27+); use C-x t o instead.
 ;; C-x t d → dired-other-tab  (Emacs 28+); use C-x t D instead.
 ("C-x t o" . treemacs-delete-other-windows)
 ("C-x t t" . treemacs)
 ("C-x t D" . treemacs-select-directory)
 ("C-x t B" . treemacs-bookmark)
 ("C-x t C-t" . treemacs-find-file)
 ("C-x t M-t" . treemacs-find-tag))
#+end_src

**** Treemacs-icons-dired

Treemacs icons for Dired.  Code is based on all-the-icons-dired.el

#+begin_src emacs-lisp
(use-package
 treemacs-icons-dired
 :after (treemacs)
 :hook (dired-mode . treemacs-icons-dired-enable-once)
 :ensure t)
#+end_src

**** Treemacs-magit -- integrate git with treemacs.

#+begin_src emacs-lisp
(use-package treemacs-magit :after (treemacs magit) :ensure t)
#+end_src


*** Treesit

Set up to use tree-sitter modes automatically, where one exists. Not
sure of the exact details of how treesit and LSP (next section) work
together. As far as I can tell, they do.

[[https://emacs-tree-sitter.github.io/][(External) Tree Sitter Docs]] (some docs here: [[info:elisp#Parsing
 Program Source][info "(elisp) Parsing Program Source"]]).

#+begin_src emacs-lisp
(use-package
 treesit-auto
 :custom (treesit-auto-install 'prompt)
 :config
 ;; Remove the markdown recipe before treesit-auto registers any mappings,
 ;; so neither auto-mode-alist nor major-mode-remap-alist ever get a
 ;; markdown entry.  We use markdown-mode instead of markdown-ts-mode.
 (setq treesit-auto-recipe-list
       (seq-remove
        (lambda (r) (eq (treesit-auto-recipe-lang r) 'markdown))
        treesit-auto-recipe-list))
 (treesit-auto-add-to-auto-mode-alist 'all)
 (global-treesit-auto-mode))
#+end_src

#+begin_src emacs-lisp
(use-package
 treesit-fold
 :vc
 (:url "https://github.com/emacs-tree-sitter/treesit-fold" :rev :newest)
 :custom (global-treesit-fold-indicators-mode t))
#+end_src

#+begin_src emacs-lisp
(use-package
 markdown-mode
 :custom
 (markdown-command
  "cmark-gfm -e footnotes -e table -e strikethrough -e autolink -e tagfilter -e tasklist --smart")
 (markdown-asymmetric-header t)
 (markdown-enable-highlighting-syntax t)
 (markdown-special-ctrl-a/e t)
 :mode
 ("\\.md\\'" . gfm-mode)
 ("\\.markdown\\'" . gfm-mode))
#+end_src

*** Flycheck

     #+BEGIN_QUOTE
     Flycheck is a modern on-the-fly syntax checking extension for GNU
     Emacs, intended as replacement for the older Flymake extension
     which is part of GNU Emacs.
     #+END_QUOTE

#+begin_src emacs-lisp
(use-package
 flycheck
 :hook (after-init . global-flycheck-mode)
 :pin "nongnu"
 :config (add-to-list 'flycheck-checkers 'org-lint))
(use-package
 flycheck-aspell
 :after flycheck
 :config
 (add-to-list 'flycheck-checkers 'markdown-aspell-dynamic)
 (add-to-list 'flycheck-checkers 'html-aspell-dynamic)
 (add-to-list 'flycheck-checkers 'xml-aspell-dynamic)
 (add-to-list 'flycheck-checkers 'c-aspell-dynamic)
 (add-to-list 'flycheck-checkers 'mail-aspell-dynamic)
 (add-to-list 'flycheck-checkers 'nroff-aspell-dynamic)
 (add-to-list 'flycheck-checkers 'tex-aspell-dynamic)
 (add-to-list 'flycheck-checkers 'texinfo-aspell-dynamic))
#+end_src

*** Python Programming

~python-ts-mode~ is a built-in mode for python using tree-sitter. Add support
for template languages used by Django and Flask frameworks.

Not hooked because templates and non-template files both end in .html. I can
manually invoke the mode, or add it with local variables.

#+begin_src emacs-lisp
(use-package jinja2-mode)
#+end_src

~elpy~ combines a selection of other utilities to create a complete python
programming environment. Defer it so it doesn't load unless we edit a python
file.

#+begin_src emacs-lisp
(use-package
 elpy
 :ensure t
 :defer t
 :commands (elpy-enable)
 :hook ((python-mode python-ts-mode) . elpy-enable))
#+end_src

*** ELisp Programming

**** Linting

#+begin_src emacs-lisp
(use-package elisp-lint :defer t)
#+end_src

**** Elisp-autofmt

This nicely formats emacs lisp code files, and the ~elisp-autofmt-region~
command works great on code embedded in .org files.

#+begin_src emacs-lisp
(use-package
 elisp-autofmt
 :defer t
 :commands (elisp-autofmt-mode elisp-autofmt-buffer elisp-autofmt-region)
 :custom
 (elisp-autofmt-format-quoted nil)
 (elisp-autofmt-use-default-override-defs t)
 ;; system python is 3.9, but elisp-autofmt needs more recent version
 (elisp-autofmt-python-bin "/opt/homebrew/bin/python3")
 (elisp-autofmt-format-quoted t)
 :hook ((emacs-lisp-mode . elisp-autofmt-mode) (lisp-data-mode . elisp-autofmt-mode))
 :bind
 (:map
  lisp-mode-shared-map
  (("C-c f" . elisp-autofmt-buffer) ("C-c r" . elisp-autofmt-region))))
#+end_src

*** Web Mode

A number of different tools allow source code to be embedded in an
HTML file. Package ~web-mode~ uses ~html-mode~ for the HTML parts, but
enables a language-specific mode for the regions of progammming
language.

#+begin_src emacs-lisp
;; see https://web-mode.org/!!
(use-package
 web-mode
 :defer t
 :mode
 (("\\.phtml\\'" . web-mode)
  ("\\.php\\'" . web-mode)
  ("\\.tpl\\'" . web-mode)
  ("\\.[agj]sp\\'" . web-mode)
  ("\\.as[cp]x\\'" . web-mode)
  ("\\.mustache\\'" . web-mode)
  ("\\.html\\'" . web-mode)
  ("\\.djhtml\\'" . web-mode))
 :custom
 (web-mode-enable-comment-interpolation t)
 (web-mode-enable-engine-detection t)
 ; this assumes we're always using django
 (web-mode-engines-alist '(("django" . "\\.html\\'"))))
#+end_src

*** Shell Scripts

#+begin_src emacs-lisp
(use-package shfmt :bind (:map sh-mode-map ("C-c C-f" . shfmt)))
#+end_src

*** Code Formatters

Run [[https://prettier.io/][Prettier]] on web-related buffers on save.

#+begin_src emacs-lisp
(use-package
 prettier
 :hook ((js-mode typescript-ts-mode css-mode web-mode html-mode))
 :custom (prettier-js-command "prettier"))
#+end_src

*** Terminal

#+begin_src emacs-lisp
(use-package vterm
  :commands vterm
  :custom (vterm-max-scrollback 10000))
#+end_src

*** Visual Tweaks

#+begin_src emacs-lisp
(use-package
 winpulse
 :vc (:url "https://github.com/xenodium/winpulse" :rev :newest)
 :config (winpulse-mode +1))
#+end_src

#+begin_src emacs-lisp
(use-package rainbow-delimiters :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

*** Language Server Protocol

Not long ago, an editor had to have custom handling written for each
language it "knew". This led to a lot of duplication of effort, and
bad editor implementations.

Now there are 2 major protocols that can be provided by language
authors to communicate information about a language to an editor. The
Language Server Protocol allows the editor to connect to an external
server process, which provides information about the language.

The Tree-Sitter protocol provides a set of shared libraries which the
editor dynamically links to, and that run in the editor's process.

Emacs now supports both methods.

This sets up lsp-mode to integrate with the LSP, and then we use a
package to integrate the information into the ~treemacs~ sidebar also.

[[https://emacs-lsp.github.io/lsp-mode//][LSP Mode Docs]]

#+begin_src emacs-lisp
(use-package
 lsp-mode
 :defer t
 :commands lsp
 ;; these are the LSP servers I have right now. Customize this for your setup!
 :hook ((sh-mode dockerfile-ts-mode sql-mode typescript-ts-mode) . 'lsp-deferred)
 :custom (lsp-enable-snippet nil) (lsp-warn-no-matched-clients nil))

(use-package lsp-treemacs :after (lsp-mode treemacs))
#+end_src

*** Org Mode

Org mode itself is set up in the ~init.el~ file (NOT generated from an .org
file), because we need to load the newer version in order to process this file
correctly.

**** Beautify Theme

#+begin_src emacs-lisp
(use-package org-beautify-theme :after org)
#+end_src

**** Add Markdown as an Export Format

#+begin_src emacs-lisp
(use-package ox-gfm :after org)
#+end_src

**** Support Syntax Highlighting in Export

#+begin_src emacs-lisp
(use-package htmlize :after org)
#+end_src

*** Vulpea (Notes)

#+begin_src emacs-lisp
(use-package vulpea :custom (vulpea-db-autosync-mode t))
(use-package vui)
(use-package vulpea-ui :bind ("C-c v s" . 'vulpea-ui-sidebar-toggle))
(use-package
 vulpea-journal
 :after (vulpea vulpea-ui)
 :config (vulpea-journal-setup)
 :bind ("C-c j" . 'vulpea-journal))
#+end_src

*** Terraform Suport

#+begin_src emacs-lisp
(use-package terraform-mode
  :ensure t
  :custom (terraform-indent-level 4)
  :config
  (defun my/terraform-mode-init ()
    (outline-minor-mode 1)
    )
  :hook (terraform-mode . my/terraform-mode-init))
#+end_src


*** CMake

Support for CMake build files and CMake-based C/C++ projects.

~cmake-mode~ provides syntax highlighting and indentation for
~CMakeLists.txt~ and ~.cmake~ files.

#+begin_src emacs-lisp
(use-package cmake-mode)
#+end_src

~cmake-project~ integrates CMake projects with Emacs's built-in
~project.el~, enabling project-aware compilation and other commands.

#+begin_src emacs-lisp
(use-package cmake-project :after cmake-mode)
#+end_src

~cmake-ide~ wires CMake compile commands into IDE features (flycheck,
auto-complete, company) by reading the project's
~compile_commands.json~.

#+begin_src emacs-lisp
(use-package cmake-ide :after cmake-mode :config (cmake-ide-setup))
#+end_src

*** Exec-path-from-shell

Gets path (and other variables) from shell and updates Emacs configuration.
Without this, on MacOS, ~load-path~ gets set from the system default, *not* the
user's environment.

#+BEGIN_QUOTE
This sets $MANPATH, $PATH and exec-path from your shell, but only when executed
in a GUI frame on OS X and Linux.
#+END_QUOTE

See also function ~exec-path-from-shell-setenv~ to import other shell variables.

#+begin_src emacs-lisp
(use-package
 exec-path-from-shell
 :config
 (when (memq window-system '(mac ns x))
   (exec-path-from-shell-initialize)
   (dolist (var '("SSH_AUTH_SOCK" "SSH_AGENT_PID" "LANG" "LC_CTYPE"))
     (add-to-list 'exec-path-from-shell-variables var))))
#+end_src

*** XKCD

The best web comic ever, available right in the editor.

#+begin_src emacs-lisp
(use-package xkcd)
#+end_src

*** AI Integration

#+begin_src emacs-lisp
  ;; disabling this until gptel gets fixed
    ;; (use-package
    ;;  gptel
    ;;  :defer t
    ;;  :pin "nongnu"
    ;;  :custom gptel-model 'claude-sonnet-4-6)
    ;;  (gptel-backend
    ;;   '(gptel-anthropic "Claude" :stream t
    ;;                     :key
    ;;                     (lambda () (getenv "ANTHROPIC_API_KEY"))))

    ;; (use-package gptel-fn-complete :after gptel)

    ;; (use-package gptel-agent :after gptel)
#+end_src

** End Of File
#+begin_src emacs-lisp
(message "config.org loaded.")
;;; config.el ends here
#+end_src
