# -*- fill-column: 80; mode: org; -*-
#+auto_export: html
#+auto_tangle: t
#+OPTIONS: toc:2
#+PROPERTY: header-args:emacs-lisp :tangle config.el

* Emacs Configuration


This is file config.org: Main emacs configuration.

** File Setup

*Must* be first line of the file.

#+begin_src emacs-lisp
;;; config.el -- Non-site-specific initialization -*- lexical-binding: t; -*-
#+end_src

Legal/copyright notice for the generated file. All terms are asserted to apply
to this file also.

#+begin_src emacs-lisp

;; Copyright © 2026 A. Lloyd Flanagan
;;
;; Author: A. Lloyd Flanagan <lloyd.flanagan@proton.me>
;; Maintainer: A. Lloyd Flanagan <lloyd.flanagan@proton.me>
;; Created: 2014
;; Version: ??

;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.
;;
;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to
;; the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
;; Boston, MA 02111-1307, USA.
;;
;; This file is not part of GNU Emacs.

;;; Commentary:
;; See config.org for documentation.
;;
;;; Code:

#+end_src


** Clipboard Tweaks

More optimizations from the blog post by [[https://emacsredux.com/blog/2026/04/07/stealing-from-the-best-emacs-configs/][Bozhidar Batsov]].

*** Keep Clipbard Contents

#+BEGIN_QUOTE
Here’s a scenario: you copy a URL from your browser, switch to Emacs, kill a
line with C-k, and then try to yank the URL you copied earlier with C-y. Gone.
The kill replaced it on the clipboard.

This setting makes Emacs save the existing clipboard content into the kill ring
before overwriting it:
#+END_QUOTE

#+begin_src emacs-lisp
(setopt save-interprogram-paste-before-kill t)
#+end_src

*** De-Duplicate Kill Ring

#+begin_src emacs-lisp
(setopt kill-do-not-save-duplicates t)
#+end_src

*** Fix find-file-at-point

The *~ffap~* function is a.k.a. *~find-file-at-point~*, and I only use it for
files. So it's a real problem when it tries to interpret the filenama as a URL,
so I turn it off.

#+begin_src emacs-lisp
(setopt ffap-machine-p-known 'reject)
#+end_src

** Easy Customization

Set up separate file for use by emacs customization.

I prefer to set customization options in the ~use-package~ declaration for each
package, but on-the-fly or local-only customizations will go to this file.

#+begin_src emacs-lisp
(defun get-config-file (filename)
          "Returns FILENAME absolute path in the user's my_emacs directory."
          (expand-file-name filename
                            (expand-file-name "my_emacs/"
                                              user-emacs-directory)))

;; custom-file is built-in global variable.
(setq custom-file (get-config-file "custom.el"))
(load custom-file 'no-error 'no-message)
#+end_src

We need to add the *melpa* package source to ~package-archives~.

#+begin_src emacs-lisp
(setopt
 package-archives
 '(("gnu" . "https://elpa.gnu.org/packages/") ("nongnu" . "https://elpa.nongnu.org/nongnu/")
   ("melpa" . "https://melpa.org/packages/")))
#+end_src

** Load Path

Emacs 31 adds ~my_emacs/lisp~ to ~load-path~ through ~user-lisp-directory~ (set
in ~early-config.org~). Older versions need it added explicitly.

#+begin_src emacs-lisp
(when (< emacs-major-version 31)
  (add-to-list 'load-path (expand-file-name "my_emacs/lisp" user-emacs-directory))
  (add-to-list
   'load-path (expand-file-name "my_emacs/lisp/org-contrib/lisp" user-emacs-directory)))
#+end_src

** Secrets File

This local file is for global variables with values which should not be checked
in with source control, such as passwords and API keys.

Mine defines a function ~define-secret-customizations~ which calls ~setopt~ to
set customization options that should be secret.

#+begin_src emacs-lisp
(if (require 'my-secrets nil 'noerror)
    (when (fboundp 'define-secret-customizations)
      (define-secret-customizations))
  (display-warning 'my-config "my-secrets.el not found on load-path" :warning))
#+end_src

** Uniquify

Uniquify is a part of emacs which is not loaded by default, but it can
be ~require~d to change the way buffers are named when editing
different files with the same name. From the source file:

#+BEGIN_QUOTE
Emacs's traditional method for making buffer names unique adds <2>, <3>, etc. to
the end of (all but one of) the buffers. This file replaces that behavior, for
buffers visiting files and Dired buffers, with a uniquification that adds parts
of the file name until the buffer names are unique.
#+END_QUOTE

#+begin_src emacs-lisp
(require 'uniquify)
(setopt uniquify-buffer-name-style 'post-forward-angle-brackets)
#+end_src

** Customizing Emacs Itself

We can use ~use-package~ to configure emacs itself as a 'pseudo-package'.

#+begin_src emacs-lisp
(use-package
 emacs

 :bind
 (("M-/" . #'hippie-expand)
  ("C-x C-b" . #'ibuffer)
  ("C-s" . #'isearch-forward-regexp)
  ("C-r" . #'isearch-backward-regexp)
  ("C-M-s" . #'isearch-forward)
  ("C-M-r" . #'isearch-backward)
  ("C-x M-r" . #'remember)

  ("C-x M-R" .
   (lambda ()
     (interactive)
     (let ((current-prefix-arg '(4)))
       (call-interactively #'remember))))
  ("s-q" . nil)
  ;; runs save-buffers-kill-emacs by default, but too easy to hit by accident
  )

 :config
 (global-auto-revert-mode)
 (when window-system
   (tool-bar-mode -1))
 (blink-cursor-mode -1)
 (when (equal system-type 'darwin)
   (setopt trash-directory "~/.Trash"))

 ;; set coding systems used to Unicode standard
 (set-terminal-coding-system 'utf-8)
 (set-keyboard-coding-system 'utf-8)
 (prefer-coding-system 'utf-8)

 (ido-mode t)
 (ido-everywhere t)

 ;; be careful with this: it can conflict with version control hooks such as
 ;; precommit (see alse ~kill-buffer-delete-auto-save-files~
 (auto-save-visited-mode t)

 (column-number-mode t) ;; displays current column in mode line
 (setq-default indent-tabs-mode nil)

 (save-place-mode t)
 (show-paren-mode t)
 (transient-mark-mode t) ;; visually highlight selected region

 (when (>= emacs-major-version 30)
   (minibuffer-regexp-mode 1) ;; syntax highlighting for writing regexps
   (setopt project-mode-line t)) ;; show clickable project name in mode line

 :custom
 (ido-big-directories '("node_modules" "\\.?venv"))
 (ido-cannot-complete-command #'ido-completion-help)
 (ido-ignore-directories '("\\`CVS/" "\\`\\.\\./" "\\`\\./" "\\`__pycache__/"))
 (ido-use-filename-at-point nil)
 (ido-use-url-at-point t)
 (ido-use-virtual-buffers 'auto)
 (ido-buffer-disable-smart-matches nil)
 (ido-create-new-buffer 'always)
 (ido-enable-dot-prefix t)
 (ido-show-dot-for-dired t)
 ;; JavaScript and CSS
 (js-chain-indent t)
 (js-enabled-frameworks '(javascript extjs))
 (js-indent-level 2)
 (css-indent-offset 2)
 ;; auto-save options
 (kill-buffer-delete-auto-save-files t)
 (delete-by-moving-to-trash t) ;; use system trash can for deleted files
 (apropos-do-all t)
 ;; put file backups in single directory, not in same directory with '~'
 ;; appended.
 (backup-directory-alist `(("." . ,(concat user-emacs-directory "backups"))))
 (use-package-compute-statistics t) ;; get useful startup timings with M-x use-package-report

 ;; old libraries are creating temporary buffers without the lexical-binding
 ;; tag. Since I don't need that warning, clean up *Warnings* a bit by silencing
 ;; it

 (warning-suppress-types '((files missing-lexbind-cookie)))
 ;; log warnings to *Warnings*, but only pop up the buffer for errors
 (warning-minimum-level :error)

 (server-log t)
 ;; use value of `truncate_lines' even in windows narrower than frame
 (truncate-partial-width-windows nil)
 (use-file-dialog nil)
 (visible-bell (not (equal system-type 'darwin))) ;;bad on mac
 ;; don't show package in menu if higher-priority package is found
 (package-menu-hide-low-priority t)

 ;; Python setup: assume mise manages uv, and uv creates .venv in each project.
 ;; Prepend .venv/bin to exec-path so python3 resolves to the project venv.
 (python-shell-exec-path '("./.venv/bin"))
 (python-interpreter "python3")
 (python-shell-interpreter "python3")
 (echo-keystrokes 0.1) ;; reduce lag in echo keystroke to sc28reen
 (fill-column 80)
 ;; use as much syntax highlighting as possible, by default
 (font-lock-maximum-decoration t)
 (inhibit-startup-message t) ;; turn off Emacs splash screen
 (initial-scratch-message nil)
 (mouse-yank-at-point t)
 (save-interprogram-paste-before-kill t)
 (save-place-file (expand-file-name "places" user-emacs-directory))
 (select-enable-clipboard t) ;; integrate emacs with system clipboard
 (select-enable-primary t)
 (selection-coding-system 'utf-8)

 ;; don't automatically double space after sentence end -- obsolete style
 (sentence-end-double-space nil)

 ;; I use the [Commonmark](httsp://commonmark.org) executable ~cmark-gfm~ for
 ;; rendering markdown files, with GitHub-flavored extensions. So I need to
 ;; tell markdown-ts-mode.
 (markdown-command
  "cmark-gfm -e footnotes -e table -e strikethrough -e tasklist --table-prefer-style-attributes --github-pre-lang --unsafe")

 :hook (prog-mode . display-line-numbers-mode)
 ;; Treat CamelCaseSubWords as separate words in every programming mode.
 (prog-mode . subword-mode))
#+end_src

** Default Font

Set up with my current programming font, Fira Code. You must have Fira
Code installed on your system for this to work.

#+begin_src emacs-lisp
;;; interesting -- family is not checked for validity
(set-face-attribute 'default nil
                    :family "FiraCode Nerd Font Mono"
                    :height 170
                    :weight 'normal
                    :slant 'normal
                    :width 'normal)
#+end_src

** Packages

~use-package~ is a nifty macro that combines package retrieval, installation,
and configuration into one declaritive statement.

*** EditorConfig

There is a standard file named .editorconfig that sets a few options for an
editor, helping ensure everyone working on a project uses the same settings.
This sets up Emacs to get config settings from that file.

#+begin_src emacs-lisp
(use-package editorconfig :config (editorconfig-mode 1))
#+end_src

*** Themes

#+begin_src emacs-lisp
;; :vc needs Emacs 30. `eval' keeps Emacs 29 from expanding (and rejecting) it.
(when (>= emacs-major-version 30)
  (eval '(use-package
          batppuccin
          :vc (:url "https://github.com/bbatsov/batppuccin-emacs" :rev :newest)
          :config (load-theme 'batppuccin-latte t))
        t))
#+end_src

*** Better Mode Line

[[https://github.com/Malabarba/smart-mode-line][Smart-mode-line]] is a sexy mode-line for Emacs. It aims to be easy to
read from small to large monitors by using colors, a prefix feature,
and smart truncation.

#+begin_src emacs-lisp
(use-package smart-mode-line :config (sml/setup))
#+end_src

*** Ido and amx

There are (at least) three major emacs packages to enable auto-completion:
"ivy", "company", and "ido". Ivy is full-featured and includes "counsel", which
modifies emacs commands to use ivy. However, it looks not to be actively
maintained, and I've come to prefer "ido". It's builtin to Emacs, which is
convenient.

Install ~ido-completing-read+~, an undeclared dependency of ~ido~.

#+BEGIN_QUOTE
This package replaces stock emacs completion with ido completion wherever it is
possible to do so without breaking things (i.e. what you were probably hoping
for when you set ido-everywhere to t).
#+END_QUOTE

#+begin_src emacs-lisp
(use-package ido-completing-read+
  :config
    (ido-ubiquitous-mode 1))
#+end_src

The [[https://github.com/DarwinAwardWinner/amx]["amx" package]] leverages "ido" to add features to the Emacs
~execute-extended-command~ function (M-x).

#+begin_src emacs-lisp
(use-package amx
    :config (amx-mode 1))
#+end_src

*** Clean up Whitespace

This package automatically strips extra whitespace from the end of
lines.

#+begin_src emacs-lisp
(use-package whitespace-cleanup-mode :config (global-whitespace-cleanup-mode 1))
#+end_src

*** Treemacs

Set up treemacs, the directory tree sidebar. See [[https://github.com/Alexander-Miller/treemacs][treemacs repo]] for all
the gory details.

#+begin_src emacs-lisp
(use-package
 treemacs
 :defer nil

 :init
 (require 'cua-base)
 (with-eval-after-load 'winum
   (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
 :config
 (when treemacs-python-executable
   (treemacs-git-mode 'extended)
   (treemacs-git-commit-diff-mode t)
   (treemacs-hide-gitignored-files-mode t))
 ;; treemacs-git-commit-diff fires async callbacks for all workspace projects,
 ;; including ones not currently visible in the buffer.  When the callback
 ;; tries to annotate a path whose project node doesn't exist in the buffer,
 ;; treemacs-project->position receives nil and crashes.  Guard against that.
 (with-eval-after-load 'treemacs-git-commit-diff-mode
   (advice-add
    'treemacs-apply-single-annotation
    :before-while (lambda (path) (treemacs-is-path path :in-workspace))))
 (treemacs-project-follow-mode 1)
 (treemacs-filewatch-mode 1)
 ;; follow mode makes it difficult to find file that are not on-screen
 (treemacs-follow-mode -1)
 ;; init.el loads this file inside `save-window-excursion', which would close a
 ;; sidebar opened now; open it once startup is finished instead.
 (add-hook 'emacs-startup-hook #'treemacs-start-on-boot)

 :custom
 (treemacs-is-never-other-window t)
 (treemacs-follow-after-init nil)

 :bind
 ;; M-0 intentionally omitted here; scoped to winum-keymap in :init above
 ;; to avoid shadowing digit-argument globally.
 ;; C-x t 1 → tab-close-other (Emacs 27+); use C-x t o instead.
 ;; C-x t d → dired-other-tab  (Emacs 28+); use C-x t D instead.
 ("C-x t o" . treemacs-delete-other-windows)
 ("C-x t t" . treemacs)
 ("C-x t D" . treemacs-select-directory)
 ("C-x t B" . treemacs-bookmark)
 ("C-x t C-t" . treemacs-find-file)
 ("C-x t M-t" . treemacs-find-tag))
#+end_src

*** Treesit

Set up to use tree-sitter modes automatically, where one exists.

[[https://emacs-tree-sitter.github.io/][(External) Tree Sitter Docs]] (some docs here: [[info:elisp#Parsing
 Program Source][info "(elisp) Parsing Program Source"]]).

#+begin_src emacs-lisp
(use-package
 treesit-auto
 :custom
 (treesit-auto-install 'prompt)
 (treesit-font-lock-level 4) ;; most detailed tree-sitter highlighting
 :config
 (treesit-auto-add-to-auto-mode-alist 'all)
 (global-treesit-auto-mode))
#+end_src

#+begin_src emacs-lisp
;; :vc needs Emacs 30. `eval' keeps Emacs 29 from expanding (and rejecting) it.
(when (>= emacs-major-version 30)
  (eval '(use-package
          treesit-fold
          :vc
          (:url "https://github.com/emacs-tree-sitter/treesit-fold" :rev :newest)
          :config (global-treesit-fold-indicators-mode 1))
        t))
#+end_src

*** Flycheck

     #+BEGIN_QUOTE
     Flycheck is a modern on-the-fly syntax checking extension for GNU
     Emacs, intended as replacement for the older Flymake extension
     which is part of GNU Emacs.
     #+END_QUOTE

*~flycheck-aspell~* integrates the spelling checker ~aspell~ into flycheck. You
need to have [[http://aspell.net][~aspell~]] installed. *~flycheck-pos-tip~* shows the flycheck error
message in a small popup window, so you don't have to look at the message.
*~flycheck-status-emoji~* shows the current flycheck status as a face emoji on
the mode line (other editors call this the status line), cute but also saves
mode line space.

#+begin_src emacs-lisp
(use-package
 flycheck
 :hook (after-init . global-flycheck-mode)
 :pin "nongnu"
 :config (add-to-list 'flycheck-checkers 'org-lint)
 ;; errcheck and go build are causing errors in flycheck
 :custom
 (flycheck-disabled-checkers '(go-errcheck go-build))
 ;; *scratch* has no file, so Emacs 30+ never trusts it and Flycheck can't check
 ;; it; skip lisp-interaction-mode instead of showing a "no checker" message.
 (flycheck-global-modes '(not lisp-interaction-mode))
 (flycheck-markdown-markdownlint-cli-config
  '(".markdownlint.json" ".markdownlint.jsonc" ".markdownlint.yaml"
    ".markdownlint"))
 (flycheck-python-ruff-executable "/opt/homebrew/bin/ruff")
 (flycheck-rubocop-lint-only t))
(use-package flycheck-pos-tip :after flycheck :config (flycheck-pos-tip-mode))
#+end_src

*** Programming Languages
**** Python

~elpy~ has traditionally been the package you install to set up python tools,
however it has not been updated to work with more recent versions of python
nor recognize the `pyproject.toml` project configuration (see
https://github.com/jorgenschaefer/elpy/issues/2052). This is true as of the
20260515.230 build.

So, I'm not installing ~elpy~ but using [[https://github.com/z80dev/uv-mode][uv-mode]]. It means setting up each python
package individually, but what's a programmer to do?

#+begin_src emacs-lisp
(use-package
 uv-mode
 :defer t
 :hook
 (python-mode . uv-mode-auto-activate-hook)
 (python-ts-mode . uv-mode-auto-activate-hook))
#+end_src

**** Elisp
***** Linting

#+begin_src emacs-lisp
(use-package elisp-lint :defer t)
#+end_src

***** Elisp-autofmt

This nicely formats emacs lisp code files, and the ~elisp-autofmt-region~
command works great on code embedded in .org files.

#+begin_src emacs-lisp
(use-package
 elisp-autofmt
 :defer t
 :commands (elisp-autofmt-mode elisp-autofmt-buffer elisp-autofmt-region)
 :custom
 (elisp-autofmt-format-quoted nil)
 (elisp-autofmt-use-default-override-defs t)
 ;; system python is 3.9, but elisp-autofmt needs more recent version
 (elisp-autofmt-python-bin "/opt/homebrew/bin/python3")
 (elisp-autofmt-format-quoted t)
 :hook (emacs-lisp-mode lisp-data-mode)
 :bind
 (:map
  lisp-mode-shared-map
  (("C-c f" . elisp-autofmt-buffer) ("C-c r" . elisp-autofmt-region))
  :map
  org-mode-map
  (("C-c r" . elisp-autofmt-region))))
#+end_src


**** Terraform Suport

#+begin_src emacs-lisp
(use-package
 terraform-mode
 :custom (terraform-indent-level 4)
 :config
 (defun my/terraform-mode-init ()
   (outline-minor-mode 1))
 :hook (terraform-mode . my/terraform-mode-init))
#+end_src

*** Zap Up To Char

In Emac's standard keybindings, the command `zap-to-char` is bound to key M-z
(alt-Z on PC, option-Z on Mac). However I find the `zap-up-to-char` command to
be more useful, so I'm rebinding the key.

#+begin_src emacs-lisp
(bind-key "M-z" #'zap-up-to-char)
#+end_src

*** Web Mode

~web-mode~ adds support for templating languages to ~html-mode~. It supports
over 20 templating languages, including Jinja. There's also a mode called
~jinja2-mode~, however it is not up-to-date with the latest Jinja versions.
~web-mode~ is much better.

#+begin_src emacs-lisp
;; see https://web-mode.org/!!
(use-package
 web-mode
 :defer t
 :mode
 (("\\.phtml\\'" . web-mode)
  ("\\.php\\'" . web-mode)
  ("\\.tpl\\'" . web-mode)
  ("\\.[agj]sp\\'" . web-mode)
  ("\\.as[cp]x\\'" . web-mode)
  ("\\.mustache\\'" . web-mode)
  ("\\.html\\'" . web-mode)
  ("\\.djhtml\\'" . web-mode))
 :custom
 (web-mode-enable-comment-interpolation t)
 (web-mode-enable-engine-detection t)
 ; this assumes we're always using django
 (web-mode-engines-alist '(("django" . "\\.html\\'"))))
#+end_src

*** Shell Scripts

#+begin_src emacs-lisp
(use-package
 shfmt
 :after sh-script
 :bind
 (:map sh-mode-map ("C-c C-f" . shfmt) :map bash-ts-mode-map ("C-c C-f" . shfmt)))
#+end_src

*** Code Formatters

Run [[https://prettier.io/][Prettier]] on web-related buffers on save.

#+begin_src emacs-lisp
(use-package
 prettier
 :defer t
 :hook
 (js-mode js-ts-mode typescript-ts-mode css-mode css-ts-mode web-mode html-mode))
#+end_src

*** Visual Tweaks

Briefly highlights the new window when you switch windows.

#+begin_src emacs-lisp
;; :vc needs Emacs 30. `eval' keeps Emacs 29 from expanding (and rejecting) it.
(when (>= emacs-major-version 30)
  (eval '(use-package
          winpulse
          :vc (:url "https://github.com/xenodium/winpulse" :rev :newest)
          :config (winpulse-mode +1))
        t))
#+end_src

This is a nifty package that colors nested delimiters according to their nesting
level, to provide a visual cue for matching delimiters. Especially helpful in
lisp modes.

#+begin_src emacs-lisp
(use-package rainbow-delimiters :hook prog-mode)
#+end_src

*** Language Server Protocol

Not long ago, an editor had to have custom handling written for each
language it "knew". This led to a lot of duplication of effort, and
bad editor implementations.

Now there are 2 major protocols that can be provided by language
authors to communicate information about a language to an editor. The
Language Server Protocol allows the editor to connect to an external
server process, which provides information about the language.

The Tree-Sitter protocol provides a set of shared libraries which the
editor dynamically links to, and that run in the editor's process.

Emacs now supports both methods.

This sets up lsp-mode to integrate with the LSP, and then we use a
package to integrate the information into the ~treemacs~ sidebar also.

[[https://emacs-lsp.github.io/lsp-mode//][LSP Mode Docs]]

#+begin_src emacs-lisp
(use-package
 lsp-mode
 :defer t
 :commands lsp
 ;; these are the LSP servers I have right now. Customize this for your setup!
 :hook
 ((sh-mode bash-ts-mode dockerfile-ts-mode sql-mode typescript-ts-mode) . 'lsp-deferred)
 :custom
 (lsp-enable-snippet nil)
 (lsp-warn-no-matched-clients nil)
 (lsp-bash-allowed-shells '(sh bash zsh))
 (lsp-javascript-format-enable nil)
 (lsp-pylsp-plugins-isort-enabled t)
 (lsp-pylsp-plugins-preload-modules [])
 (lsp-pylsp-plugins-ruff-enabled t)
 (lsp-pylsp-plugins-ruff-exclude [])
 (lsp-pylsp-plugins-ruff-extend-ignore [])
 (lsp-pylsp-plugins-ruff-format [])
 (lsp-pylsp-plugins-ruff-ignore [])
 (lsp-pylsp-plugins-ruff-select [])
 (lsp-pylsp-server-command '("uv" "run" "pylsp"))
 (lsp-rubocop-use-bundler t)
 (lsp-ruby-lsp-use-bundler t)
 (lsp-typescript-format-enable nil)
 (lsp-typescript-tsserver-trace "messages"))

(use-package lsp-treemacs :after (lsp-mode treemacs))
#+end_src

*** Org Mode

Org mode itself is set up in the ~init.el~ file (NOT generated from an .org
file), because we need to load the newer version in order to process this file
correctly.

**** Add Markdown as an Export Format

#+begin_src emacs-lisp
(use-package ox-gfm :after org)
#+end_src

**** Support Syntax Highlighting in Export

#+begin_src emacs-lisp
(use-package htmlize :defer t :after org)
#+end_src

**** Add option for auto-tangling org-babel files like this one

#+begin_src emacs-lisp
(use-package org-auto-tangle :defer t :hook org-mode)
#+end_src

**** Automatically Tangle Org Files on Save

#+begin_src emacs-lisp
(use-package org-autoexport
  :defer t
  :hook (org-mode . org-autoexport-mode))
#+end_src

A much more visually appealing mode for editing .org files.

#+begin_src emacs-lisp
(use-package org-modern :config (global-org-modern-mode))
#+end_src

*** CMake

Support for CMake build files and CMake-based C/C++ projects.

~cmake-mode~ provides syntax highlighting and indentation for
~CMakeLists.txt~ and ~.cmake~ files.

#+begin_src emacs-lisp
(use-package cmake-mode)
#+end_src

~cmake-project~ integrates CMake projects with Emacs's built-in
~project.el~, enabling project-aware compilation and other commands.

#+begin_src emacs-lisp
(use-package cmake-project :after cmake-mode)
#+end_src

~cmake-ide~ wires CMake compile commands into IDE features (flycheck,
auto-complete, company) by reading the project's
~compile_commands.json~.


#+begin_src emacs-lisp
(use-package cmake-ide :after cmake-mode :config (cmake-ide-setup))
#+end_src

*** XKCD

The best web comic ever, available right in the editor.

#+begin_src emacs-lisp
(use-package xkcd :defer t)
#+end_src

** End Of File
#+begin_src emacs-lisp
(message "config.org loaded.")
;;; config.el ends here
#+end_src
