;; -*- lexical-binding: t -*-

;;
;; DO NOT EDIT THIS FILE
;; It is produced by tangling the file early-config.org, and may be
;; overwritten. Edit that file, then execute the `org-babel-tangle'
;; command.

(require 'autorevert)
(setopt gc-cons-threshold most-positive-fixnum)

(add-hook
 'emacs-startup-hook (lambda () (setopt gc-cons-threshold (* 5 1024 1024))))

;; (setopt garbage-collection-messages t) ;; show GC messages for debugging

(if (equal system-type 'darwin)
    (setenv
     "LIBRARY_PATH"
     (string-join
      '("/opt/homebrew/opt/gcc/lib/gcc/current"
        "/opt/homebrew/opt/libgccjit/lib/gcc/current"
        ;; this directory, alas, has no "current" symlink. You'll need to fix every time
        ;; gcc is updated. Or we need code to find it dynamically.
        "/opt/homebrew/Cellar/gcc/15.2.0_1/lib/gcc/current/gcc/aarch64-apple-darwin25/15/")
      ":")))

(setopt initial-frame-alist
        '((horizontal-scroll-bars)
          (vertical-scroll-bars)
          (width . 150)
          (height . 40)))

(push '(menu-bar-lines . 0) default-frame-alist)
(push '(tool-bar-lines . 0) default-frame-alist)

(setopt load-prefer-newer t)

(if (boundp 'user-lisp-directory)
    (setopt user-lisp-directory (concat user-emacs-directory "my_emacs/lisp")))

;; Local Variables:
;; no-byte-compile: t
;; no-native-compile: t
;; no-update-autoloads: t
;; End:

;;; early-init.el ends here
