;; -*- lexical-binding: t -*-

;;
;; DO NOT EDIT THIS FILE
;; It is produced by tangling the file early-config.org, and may be
;; overwritten. Edit that file, then execute the `org-babel-tangle'
;; command.

(setopt gc-cons-threshold most-positive-fixnum)

(add-hook
 'emacs-startup-hook (lambda () (setopt gc-cons-threshold (* 5 1024 1024))))
;; (setopt garbage-collection-messages t) ;; show GC messages for debugging

(when (equal system-type 'darwin)
  (setenv "LIBRARY_PATH"
          (string-join
           `("/opt/homebrew/opt/gcc/lib/gcc/current"
             "/opt/homebrew/opt/libgccjit/lib/gcc/current"
             ,(car
               (file-expand-wildcards
                "/opt/homebrew/Cellar/gcc/*/lib/gcc/current/gcc/*/*")))
           ":")))

(setopt initial-frame-alist
        '((horizontal-scroll-bars)
          (vertical-scroll-bars)
          (width . 150)
          (height . 40)))

(push '(menu-bar-lines . 0) default-frame-alist)
(push '(tool-bar-lines . 0) default-frame-alist)

(setopt load-prefer-newer t)

(when (boundp 'user-lisp-directory)
  (setopt user-lisp-directory (concat user-emacs-directory "my_emacs/lisp")))

;; Local Variables:
;; no-byte-compile: t
;; no-native-compile: t
;; no-update-autoloads: t
;; eval: (add-hook 'after-save-hook #'org-babel-tangle nil t)
;; End:

;;; early-init.el ends here
