;; -*- lexical-binding: t -*-

;;
;; DO NOT EDIT THIS FILE
;; It is produced by tangling the file early-config.org, and may be
;; overwritten. Edit that file, then execute the `org-babel-tangle'
;; command.

(setopt gc-cons-threshold most-positive-fixnum)

(add-hook 'emacs-startup-hook
    (lambda () (setopt gc-cons-threshold (* 5 1024 1024))))

(setopt garbage-collection-messages t) ;; show GC messages for debugging

(if (equal system-type 'darwin)
       (setenv
        "LIBRARY_PATH"
        (string-join
         '("/opt/homebrew/opt/gcc/lib/gcc/13"
           "/opt/homebrew/opt/libgccjit/lib/gcc/13"
           "/opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc/aarch64-apple-darwin23/13")
         ":")))

(setopt initial-frame-alist
      '((horizontal-scroll-bars)
        (vertical-scroll-bars)
        (width . 150)
        (height . 40)))

(push '(menu-bar-lines . 0) default-frame-alist)
(push '(tool-bar-lines . 0) default-frame-alist)

(setopt load-prefer-newer t)

;;; early-init.el ends here
